// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "product";

export interface CreateProductRequest {
  name: string;
  description: string;
  category: string;
  price: number;
  images: string[];
  specifications: { [key: string]: string };
}

export interface CreateProductRequest_SpecificationsEntry {
  key: string;
  value: string;
}

export interface PublishProductRequest {
  id: string;
}

export interface UpdateProductRequest {
  id: string;
  name: string;
  description: string;
  category: string;
  price: number;
  images: string[];
  specifications: { [key: string]: string };
}

export interface UpdateProductRequest_SpecificationsEntry {
  key: string;
  value: string;
}

export interface GetProductRequest {
  id: string;
}

export interface DeleteProductRequest {
  id: string;
}

export interface ListProductsRequest {
  page: number;
  limit: number;
  category: string;
  search: string;
}

export interface ProductResponse {
  id: string;
  name: string;
  category: string;
  price: number;
  images: string[];
  specifications: { [key: string]: string };
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProductResponse_SpecificationsEntry {
  key: string;
  value: string;
}

export interface ProductListResponse {
  products: ProductResponse[];
  total: number;
  page: number;
  limit: number;
}

export interface UpdateInventoryRequest {
  productId: string;
  quantity: number;
}

export interface GetInventoryRequest {
  productId: string;
}

export interface ReserveStockRequest {
  productId: string;
  quantity: number;
}

export interface ReleaseStockRequest {
  productId: string;
  quantity: number;
}

export interface InventoryResponse {
  productId: string;
  availableQuantity: number;
  reservedQuantity: number;
  totalQuantity: number;
  updatedAt: string;
}

export interface Empty {
}

export const PRODUCT_PACKAGE_NAME = "product";

export interface ProductServiceClient {
  createProduct(request: CreateProductRequest): Observable<ProductResponse>;

  getProduct(request: GetProductRequest): Observable<ProductResponse>;

  updateProduct(request: UpdateProductRequest): Observable<ProductResponse>;

  deleteProduct(request: DeleteProductRequest): Observable<Empty>;

  listProducts(request: ListProductsRequest): Observable<ProductListResponse>;

  publishProduct(request: PublishProductRequest): Observable<ProductResponse>;

  updateInventory(request: UpdateInventoryRequest): Observable<InventoryResponse>;

  getInventory(request: GetInventoryRequest): Observable<InventoryResponse>;

  reserveStock(request: ReserveStockRequest): Observable<InventoryResponse>;

  releaseStock(request: ReleaseStockRequest): Observable<InventoryResponse>;
}

export interface ProductServiceController {
  createProduct(
    request: CreateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  getProduct(request: GetProductRequest): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  updateProduct(
    request: UpdateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  deleteProduct(request: DeleteProductRequest): Promise<Empty> | Observable<Empty> | Empty;

  listProducts(
    request: ListProductsRequest,
  ): Promise<ProductListResponse> | Observable<ProductListResponse> | ProductListResponse;

  publishProduct(
    request: PublishProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  updateInventory(
    request: UpdateInventoryRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;

  getInventory(
    request: GetInventoryRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;

  reserveStock(
    request: ReserveStockRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;

  releaseStock(
    request: ReleaseStockRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createProduct",
      "getProduct",
      "updateProduct",
      "deleteProduct",
      "listProducts",
      "publishProduct",
      "updateInventory",
      "getInventory",
      "reserveStock",
      "releaseStock",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
