// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "product";

export interface CreateProductRequest {
  name: string;
  description: string;
  category: string;
  price: number;
  images: string[];
  specifications: { [key: string]: string };
  initialStock: number;
}

export interface CreateProductRequest_SpecificationsEntry {
  key: string;
  value: string;
}

export interface PublishProductRequest {
  id: string;
}

export interface UpdateProductRequest {
  id: string;
  name: string;
  description: string;
  category: string;
  price: number;
  images: string[];
  specifications: { [key: string]: string };
}

export interface UpdateProductRequest_SpecificationsEntry {
  key: string;
  value: string;
}

export interface GetProductRequest {
  id: string;
}

export interface DeleteProductRequest {
  id: string;
}

export interface ListProductsRequest {
  page: number;
  limit: number;
  category: string;
  search: string;
}

export interface ProductResponse {
  id: string;
  name: string;
  category: string;
  price: number;
  images: string[];
  specifications: { [key: string]: string };
  status: string;
  createdAt: string;
  updatedAt: string;
  description: string;
}

export interface ProductResponse_SpecificationsEntry {
  key: string;
  value: string;
}

export interface ProductListResponse {
  products: ProductResponse[];
  total: number;
  page: number;
  limit: number;
}

export interface UpdateInventoryRequest {
  productId: string;
  quantity: number;
}

export interface GetInventoryRequest {
  productId: string;
}

export interface ReserveStockRequest {
  productId: string;
  quantity: number;
}

export interface ReleaseStockRequest {
  productId: string;
  quantity: number;
}

export interface InventoryResponse {
  productId: string;
  availableQuantity: number;
  reservedQuantity: number;
  totalQuantity: number;
  updatedAt: string;
}

export interface Empty {
}

export const PRODUCT_PACKAGE_NAME = "product";

/** ProductService provides product and inventory management operations */

export interface ProductServiceClient {
  /** CreateProduct creates a new product */

  createProduct(request: CreateProductRequest): Observable<ProductResponse>;

  /** GetProduct retrieves a product by ID */

  getProduct(request: GetProductRequest): Observable<ProductResponse>;

  /** UpdateProduct updates an existing product */

  updateProduct(request: UpdateProductRequest): Observable<ProductResponse>;

  /** DeleteProduct removes a product */

  deleteProduct(request: DeleteProductRequest): Observable<Empty>;

  /** ListProducts retrieves a paginated list of products */

  listProducts(request: ListProductsRequest): Observable<ProductListResponse>;

  /** PublishProduct publishes a product */

  publishProduct(request: PublishProductRequest): Observable<ProductResponse>;

  /** UpdateInventory updates product inventory quantity */

  updateInventory(request: UpdateInventoryRequest): Observable<InventoryResponse>;

  /** GetInventory retrieves current inventory status */

  getInventory(request: GetInventoryRequest): Observable<InventoryResponse>;

  /** ReserveStock reserves stock for a product */

  reserveStock(request: ReserveStockRequest): Observable<InventoryResponse>;

  /** ReleaseStock releases reserved stock */

  releaseStock(request: ReleaseStockRequest): Observable<InventoryResponse>;
}

/** ProductService provides product and inventory management operations */

export interface ProductServiceController {
  /** CreateProduct creates a new product */

  createProduct(
    request: CreateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  /** GetProduct retrieves a product by ID */

  getProduct(request: GetProductRequest): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  /** UpdateProduct updates an existing product */

  updateProduct(
    request: UpdateProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  /** DeleteProduct removes a product */

  deleteProduct(request: DeleteProductRequest): Promise<Empty> | Observable<Empty> | Empty;

  /** ListProducts retrieves a paginated list of products */

  listProducts(
    request: ListProductsRequest,
  ): Promise<ProductListResponse> | Observable<ProductListResponse> | ProductListResponse;

  /** PublishProduct publishes a product */

  publishProduct(
    request: PublishProductRequest,
  ): Promise<ProductResponse> | Observable<ProductResponse> | ProductResponse;

  /** UpdateInventory updates product inventory quantity */

  updateInventory(
    request: UpdateInventoryRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;

  /** GetInventory retrieves current inventory status */

  getInventory(
    request: GetInventoryRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;

  /** ReserveStock reserves stock for a product */

  reserveStock(
    request: ReserveStockRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;

  /** ReleaseStock releases reserved stock */

  releaseStock(
    request: ReleaseStockRequest,
  ): Promise<InventoryResponse> | Observable<InventoryResponse> | InventoryResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createProduct",
      "getProduct",
      "updateProduct",
      "deleteProduct",
      "listProducts",
      "publishProduct",
      "updateInventory",
      "getInventory",
      "reserveStock",
      "releaseStock",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
