// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

export interface RegisterRequest {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  user: UserResponse | undefined;
}

export interface GetUserRequest {
  id: string;
}

export interface UpdateProfileRequest {
  id: string;
  firstName: string;
  lastName: string;
}

export interface VerifyEmailRequest {
  id: string;
}

export interface ValidateTokenRequest {
  token: string;
}

export interface ValidateTokenResponse {
  valid: boolean;
  userId: string;
  roles: string[];
}

export interface UserResponse {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  roles: string[];
  isActive: boolean;
  isEmailVerified: boolean;
  createdAt: string;
  fullName: string;
}

export const USERS_PACKAGE_NAME = "users";

export interface UserServiceClient {
  register(request: RegisterRequest): Observable<UserResponse>;

  login(request: LoginRequest): Observable<LoginResponse>;

  getUser(request: GetUserRequest): Observable<UserResponse>;

  updateProfile(request: UpdateProfileRequest): Observable<UserResponse>;

  verifyEmail(request: VerifyEmailRequest): Observable<UserResponse>;

  validateToken(request: ValidateTokenRequest): Observable<ValidateTokenResponse>;
}

export interface UserServiceController {
  register(request: RegisterRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateProfile(request: UpdateProfileRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  verifyEmail(request: VerifyEmailRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  validateToken(
    request: ValidateTokenRequest,
  ): Promise<ValidateTokenResponse> | Observable<ValidateTokenResponse> | ValidateTokenResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login", "getUser", "updateProfile", "verifyEmail", "validateToken"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
